### PR TITLE
robonomics-test-network-manual

### PR DESCRIPTION
**Pull request by dergudzon**

### CODE REVIEW

**Review by Vourhey — COMMENTED** [review]
Thanks for the effort. Could you translate it in english so I could submit it in the wiki?

**Comment by dergudzon** [comment]
> Thanks for the effort. Could you translate it in english so I could submit it in the wiki?

Yep, I can try to do it)

**Comment by Vourhey** [comment]
I'll help with the translation, just commit what you are able to do

**Comment by dergudzon** [comment]
Ready.

**Pull request merged**
